name = "fluence-lead-scanner"
main = "src/index.js"
compatibility_date = "2025-04-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "fluence-leads"
database_id = "1d3011db-c2d0-49d2-9da5-04e82529728a"

[env.production]
vars = { ENVIRONMENT = "production" }

# Routes
routes = [
  { pattern = "fluence-lead-scanner-api.maitilupas.workers.dev", zone_id = "2348c78bf85b27e6a55e5ec04fb8aaa6" }
]
